### PR TITLE
Basic statistics area, something to build on 

### PR DESCRIPTION
**Pull request by culther0**
yayhooray.net/awards

Probably needs icons / thought out awards,

### CODE REVIEW

**Comment by notjosh** [comment]
how come this touches `DbClient.py` and `sphinx.conf`? and `timer.log` should probably be gitignore'd

**Comment by notjosh** [comment]
and I'd ask (but not expect, really) that controllers include a JSON response for the API. I'll add it if you don't, though.

**Comment by culther0** [comment]
oh, not sure.  Probably my config or something.

**Comment by cham** [comment]
dude do you think you could make a separate PR for these without the timer, sphynx and DbClient changes? I see they've been removed, would be cleaner to not have the additions and deletes in history tho

**Comment by culther0** [comment]
ok The commits should be squashed and the errant files should be removed.

**Pull request merged**
